variables:
  PYTHONVERSION: "3.8"
  IMAGE_TAG: $CI_REGISTRY/jksoftware1/docker-python:$CI_COMMIT_REF_SLUG

services:
  - docker:20.10.21-dind

default:
  image: docker:20.10.21
  tags:
    - "saas-linux-small-amd64"
    - "docker"

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != ""

stages:
  - build

build-image:
  stage: build
  before_script:
    - echo "$CI_BUILD_TOKEN" | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  script:
    - echo "Building image with tag '$IMAGE_TAG'"
    - docker build -t $IMAGE_TAG --pull --progress=plain --build-arg PYTHONVERSION=$PYTHONVERSION .
    - docker push $IMAGE_TAG

